main: ${main.class}
name: ${project.name}
version: ${project.version}

description: Core plugin for BA Zandpoort's Minecraft server
api-version: 1.13
author: ${author}

website: cedricverlinden.com
depend: [ "WorldGuard" ]

# COMMANDS AND PERMISSIONS REGISTRATION

commands:
  region:
    description: Region command
    aliases: [ regions ]
    permission: core.command.region
    permission-message: You do not have the required permissions to execute this command.
    usage: "Usage: /<command>"
  lecture:
    description: Lecture command
    aliases: [ regions ]
    permission: core.command.lecture
    permission-message: You do not have the required permissions to execute this command.
    usage: "Usage: /<command>"

permissions:
  core.command.all:
    description: Allows you to execute all existing commands.
    default: true
    children:
      core.command.region: true
      core.command.lecture: true