main: ${main.class}
name: ${project.name}
version: ${project.version}

description: Core plugin for BA Zandpoort's Minecraft server
api-version: 1.13
author: ${author}

website: cedricverlinden.com
depend: [ "WorldGuard" ]

# COMMANDS AND PERMISSIONS REGISTRATION

commands:
  oefening:
    description: Oefening command
    aliases: [  ]
    permission: core.command.oefening
    permission-message: You do not have the required permissions to execute this command.
    usage: "Usage: /<command>"
  region:
    description: Region command
    aliases: [ regions ]
    permission: core.command.region
    permission-message: You do not have the required permissions to execute this command.
    usage: "Usage: /<command>"
  playermanager:
    description: Player manager command
    aliases: [ pm ]
    permission: core.command.playermanager
    permission-message: You do not have the required permissions to execute this command.
    usage: "Usage: /<command>"
  vanish:
    description: Vanish command
    aliases: [ ]
    permission: core.command.vanish
    permission-message: You do not have the required permissions to execute this command.
    usage: "Usage: /<command>"

permissions:
  core.command.player.all:
    description: Allows you to execute all existing player commands.
    default: true
    children:
      core.command.oefening: true
  core.command.admin.all:
    description: Allows you to execute all existing admin commands.
    default: false
    children:
      core.command.region: true
      core.command.playermanager: true
      core.command.vanish: true
  core.command.all:
    description: Allows you to execute all existing commands.
    default: false
    children:
      core.command.oefening: true
      core.command.region: true
      core.command.playermanager: true
      core.command.vanish: true